server_version: 1.0.0
server_url: https://github.com/credentials/irma_api_server/releases/download/v{{ server_version }}/irma_api_server.zip
conf_path: /etc/irma_api_server
base_install_path: /opt
install_path: /opt/irma_api_server
http_port: 8081
https_port: 8444
