- hosts: apiserver
  roles:
    - { role: preliminary, tags: ['all', 'setup', 'preliminary'] }
    - { role: apiserver,   tags: ['all', 'setup', 'apiserver'] }
    - { role: nginx,       tags: ['all', 'nginx'] }
    - { role: certbot,     tags: ['certbot'] }
